# Generated by Django 3.2.4 on 2021-07-08 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_auto_20210708_1626'),
    ]

    operations = [
        migrations.RenameField(
            model_name='places',
            old_name='lon',
            new_name='lng',
        ),
    ]
