# Generated by Django 3.2.4 on 2021-07-09 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0003_rename_lon_places_lng'),
    ]

    operations = [
        migrations.AddField(
            model_name='images',
            name='meta',
            field=models.TextField(blank=True, null=True),
        ),
    ]
